server.port=8001

spring.application.name=dormitory-management

spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.jackson.serialization.write-dates-as-timestamps=false

# CORS configuration
cors.allowed-origins=http://localhost:3001

# Task scheduling
spring.task.scheduling.pool.size=5
